@Starbucks.Api_HostAddress = http://localhost:5012

GET {{ Starbucks.Api_HostAddress }}/api/Category
Accept: application/json

###


POST {{ Starbucks.Api_HostAddress }}/api/Coffee
Accept: application/json
Content-Type: application/json

{
    "Name" : "Caffe butelo",
    "Description" : "es muy bueno y querido por los viajerons",
    "Price" : 700,
    "CategoryId" : 2,
    "Imagen" : ""
}

###