@Starbucks.Api_HostAddress = http://localhost:5012

GET {{ Starbucks.Api_HostAddress }}/api/Category
Accept: application/json

###


POST {{ Starbucks.Api_HostAddress }}/api/Coffee
Accept: application/json
Content-Type: application/json

{
    "Name" : "Cafe Santo Domingo",
    "Description" : "El mejor caffe del caribe",
    "Price" : 200,
    "CategoryId" : 1,
    "Imagen" : ""
}

###